'use client';

import { useState, useEffect } from 'react';

export type Language = 'EN' | 'FR' | 'RW';

const categoryTranslations = {
  EN: {
    'Fresh Food': 'Fresh Food',
    'Food Cupboard': 'Food Cupboard',
    'Beverages': 'Beverages',
    'Baby Products': 'Baby Products',
    'Health & Beauty': 'Health & Beauty',
    'Household & Cleaning': 'Household & Cleaning',
    'Electronics & Kitchenware': 'Electronics & Kitchenware',
  },
  FR: {
    'Fresh Food': 'Produits Frais',
    'Food Cupboard': 'Épicerie',
    'Beverages': 'Boissons',
    'Baby Products': 'Produits pour Bébés',
    'Health & Beauty': 'Santé et Beauté',
    'Household & Cleaning': 'Maison et Nettoyage',
    'Electronics & Kitchenware': 'Électronique et Cuisine',
  },
  RW: {
    'Fresh Food': 'Ibiribwa Bishya',
    'Food Cupboard': 'Ibikenerwa mu Gikoni',
    'Beverages': 'Ibinyobwa',
    'Baby Products': 'Iby\'Abana',
    'Health & Beauty': 'Isuku n\'Ubuzima',
    'Household & Cleaning': 'Isuku yo mu Rugo',
    'Electronics & Kitchenware': 'Ibijyanye n\'Ikoranabuhanga',
  }
};

const translations = {
  EN: {
    heroTitle: "Rwanda's #1 Supermarket",
    heroSubtitle: "Freshness Delivered to Your Door or Ready for Pick-up.",
    heroDescription: "Shop Rwanda's best groceries, electronics, and daily essentials with instant MoMo checkout.",
    startShopping: "Start Shopping",
    ourStores: "Our Stores",
    fastDelivery: "45-min Delivery",
    fastDeliveryDesc: "Kigali within 45 minutes",
    secureMoMo: "Secure MoMo",
    secureMoMoDesc: "100% encrypted payments",
    freshProducts: "Fresh Products",
    freshProductsDesc: "Guaranteed quality",
    search: "Search products, brands, categories...",
    cart: "Cart",
    signIn: "Sign In",
    categories: "Categories",
    allProducts: "All Products",
    recommended: "Recommended for you",
    addToCart: "Add to Cart",
    total: "Total",
    checkout: "Checkout",
    sortBy: "Sort by",
    popularity: "Popularity",
    lowToHigh: "Price: Low to High",
    highToLow: "Price: High to Low",
    categoriesList: categoryTranslations.EN,
    pickup: "Pick-up",
    delivery: "Delivery",
    selectBranch: "Select Branch",
    pickupTime: "Pick-up Time",
    momoDeposit: "MoMo Deposit",
    confirmOrder: "Confirm Order",
    noProducts: "No products found",
    outOfStock: "Out of stock",
    orderStatus: "Order Status",
    readyForPickup: "Ready for Pick-up",
    pending: "Pending",
    completed: "Completed",
    recipientName: "Recipient Name",
    phone: "MoMo Phone Number",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    depositRequired: "MoMo Deposit Required",
    depositDesc: "To confirm your pick-up, a non-refundable deposit of 500 RWF is required.",
    confirmAndPay: "Confirm & Pay Deposit",
    branchReviews: "Branch Reviews",
    checkPhone: "Check your phone!",
    momoPromptDesc: "We sent a prompt to your phone. Enter your PIN to pay the deposit.",
    iHavePaid: "I have paid",
  },
  FR: {
    heroTitle: "Le Supermarché n°1 du Rwanda",
    heroSubtitle: "Fraîcheur livrée à votre porte ou prête à être récupérée.",
    heroDescription: "Achetez les meilleurs produits d'épicerie, d'électronique et d'essentiels quotidiens du Rwanda avec paiement MoMo instantané.",
    startShopping: "Commencer vos achats",
    ourStores: "Nos Magasins",
    fastDelivery: "Livraison 45-min",
    fastDeliveryDesc: "Kigali en 45 minutes",
    secureMoMo: "MoMo Sécurisé",
    secureMoMoDesc: "Paiements 100% cryptés",
    freshProducts: "Produits Frais",
    freshProductsDesc: "Qualité garantie",
    search: "Rechercher des produits, marques...",
    cart: "Panier",
    signIn: "Se connecter",
    categories: "Catégories",
    allProducts: "Tous les produits",
    recommended: "Recommandé pour vous",
    addToCart: "Ajouter au panier",
    total: "Total",
    checkout: "Commander",
    sortBy: "Trier par",
    popularity: "Popularité",
    lowToHigh: "Prix: Croissant",
    highToLow: "Prix: Décroissant",
    categoriesList: categoryTranslations.FR,
    pickup: "Retrait",
    delivery: "Livraison",
    selectBranch: "Choisir la succursale",
    pickupTime: "Heure de retrait",
    momoDeposit: "Dépôt MoMo",
    confirmOrder: "Confirmer la commande",
    noProducts: "Aucun produit trouvé",
    outOfStock: "Rupture de stock",
    orderStatus: "Statut de la commande",
    readyForPickup: "Prêt pour le retrait",
    pending: "En attente",
    completed: "Terminé",
    recipientName: "Nom du destinataire",
    phone: "Numéro MoMo",
    orderSummary: "Résumé de la commande",
    subtotal: "Sous-total",
    depositRequired: "Dépôt MoMo requis",
    depositDesc: "Pour confirmer votre retrait, un dépôt non remboursable de 500 RWF est requis.",
    confirmAndPay: "Confirmer et payer le dépôt",
    branchReviews: "Avis sur la succursale",
    checkPhone: "Vérifiez votre téléphone!",
    momoPromptDesc: "Nous avons envoyé une notification. Entrez votre PIN pour payer le dépôt.",
    iHavePaid: "J'ai payé",
  },
  RW: {
    heroTitle: "Simba Supermarket ya mbere mu Rwanda",
    heroSubtitle: "Ibiribwa bishya byagejejwe iwawe cyangwa biteguye gufatwa.",
    heroDescription: "Gura ibiribwa byiza, ibikoresho by'ikoranabuhanga, n'ibindi by'ibanze ukoresheje MoMo.",
    startShopping: "Tangira Gura",
    ourStores: "Amaduka yacu",
    fastDelivery: "Iminota 45",
    fastDeliveryDesc: "Muri Kigali mu minota 45",
    secureMoMo: "MoMo Ifite Umutekano",
    secureMoMoDesc: "Kwishura bifite umutekano 100%",
    freshProducts: "Ibiribwa Bishya",
    freshProductsDesc: "Ubwiza bwizewe",
    search: "Shaka ibicuruzwa...",
    cart: "Ikarita",
    signIn: "Injira",
    categories: "Ibyiciro",
    allProducts: "Ibicuruzwa byose",
    recommended: "Ibyatoranyijwe",
    addToCart: "Shyira mu ikarita",
    total: "Hose",
    checkout: "Ishura",
    sortBy: "Tondeka",
    popularity: "Ibikunzwe",
    lowToHigh: "Igiciro: Gito",
    highToLow: "Igiciro: Kinini",
    categoriesList: categoryTranslations.RW,
    pickup: "Gufata",
    delivery: "Kugezwaho",
    selectBranch: "Hitamo Ishami",
    pickupTime: "Igihe cyo gufata",
    momoDeposit: "Ingwate ya MoMo",
    confirmOrder: "Emeza Iyakira",
    noProducts: "Nta bicuruzwa byabonetse",
    outOfStock: "Byashize",
    orderStatus: "Imiterere y'iyakira",
    readyForPickup: "Biteguye gufatwa",
    pending: "Bitegereje",
    completed: "Byarangiye",
    recipientName: "Izina ry'uwakira",
    phone: "Nimero ya MoMo",
    orderSummary: "Incamake",
    subtotal: "Igiteranyo gito",
    depositRequired: "Ingwate ya MoMo irakenewe",
    depositDesc: "Kugira ngo wemereze gufata ibintu, ubanza kwishyura 500 RWF nk'ingwate.",
    confirmAndPay: "Emeza kandi wishyure",
    branchReviews: "Ibitekerezo ku ishami",
    checkPhone: "Reba muri terefoni yawe!",
    momoPromptDesc: "Tukwoherereje ubutumwa muri terefoni. Shyiramo PIN yawe wishyure ingwate.",
    iHavePaid: "Namaze kwishyura",
  }
};

export function useLanguage() {
  const [lang, setLang] = useState<Language>('EN');

  useEffect(() => {
    const saved = localStorage.getItem('simba_lang') as Language;
    if (saved && translations[saved]) {
      setLang(saved);
    }
  }, []);

  const changeLanguage = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem('simba_lang', newLang);
  };

  return { lang, t: translations[lang], changeLanguage };
}
